import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List


class ReportGenerator:
    """
    Generate structured review reports for the Research Contract Adviser Agent.

    The report groups clause-level comparison results into:
    - Green Flags
    - Amber Flags
    - Red Flags
    - Blue Flags

    This report is for human review support only and does not provide legal advice.
    """

    FLAG_ORDER = ["Red", "Amber", "Blue", "Green"]

    FLAG_LABELS = {
        "Green": "Green Flags - Appears aligned with UoA reference positions",
        "Amber": "Amber Flags - Requires contract manager review",
        "Red": "Red Flags - Potential conflict or high-risk deviation",
        "Blue": "Blue Flags - Not clearly covered by available references",
    }

    def build_report_payload(
        self,
        file_name: str,
        contract_type: str,
        classification_confidence: float,
        results: List[Dict[str, object]],
    ) -> Dict[str, object]:
        grouped = self._group_by_flag(results)

        return {
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "file_name": file_name,
            "predicted_contract_type": contract_type,
            "classification_confidence": classification_confidence,
            "total_clauses_reviewed": len(results),
            "flag_counts": {
                "Green": len(grouped["Green"]),
                "Amber": len(grouped["Amber"]),
                "Red": len(grouped["Red"]),
                "Blue": len(grouped["Blue"]),
            },
            "grouped_results": grouped,
            "disclaimer": (
                "This report is generated by an experimental proof-of-concept system. "
                "It supports human review only and does not provide legal advice or final contract approval."
            ),
        }

    def to_markdown(self, payload: Dict[str, object]) -> str:
        lines = []

        lines.append("# Research Contract Adviser Agent - Review Report")
        lines.append("")
        lines.append("## 1. Report Summary")
        lines.append("")
        lines.append(f"- **Generated At:** {payload['generated_at']}")
        lines.append(f"- **File Name:** {payload['file_name']}")
        lines.append(f"- **Predicted Contract Type:** {payload['predicted_contract_type']}")
        lines.append(f"- **Classification Confidence:** {payload['classification_confidence']:.2f}")
        lines.append(f"- **Total Clauses Reviewed:** {payload['total_clauses_reviewed']}")
        lines.append("")
        lines.append("## 2. Flag Counts")
        lines.append("")
        lines.append("| Flag | Count |")
        lines.append("|---|---:|")

        for flag in ["Red", "Amber", "Blue", "Green"]:
            lines.append(f"| {flag} | {payload['flag_counts'][flag]} |")

        lines.append("")
        lines.append("## 3. Important Notice")
        lines.append("")
        lines.append(payload["disclaimer"])
        lines.append("")
        lines.append("---")
        lines.append("")

        grouped = payload["grouped_results"]

        for flag in self.FLAG_ORDER:
            lines.append(f"## 4.{self.FLAG_ORDER.index(flag) + 1} {self.FLAG_LABELS[flag]}")
            lines.append("")

            items = grouped.get(flag, [])

            if not items:
                lines.append("_No clauses in this category._")
                lines.append("")
                continue

            for item in items:
                lines.append(
                    f"### Clause {item['clause_number']}: {item['clause_title']}"
                )
                lines.append("")
                lines.append(f"- **Topic:** {item['topic']}")
                lines.append(f"- **Flag:** {item['flag']}")
                lines.append(f"- **Alignment:** {item['alignment']}")
                lines.append(f"- **Confidence:** {item['confidence']}")
                lines.append(f"- **Human Review Required:** {item['human_review_required']}")
                lines.append("")
                lines.append("**Clause Text:**")
                lines.append("")
                lines.append("> " + self._single_line(item["clause_text"]))
                lines.append("")
                lines.append("**Rationale:**")
                lines.append("")
                lines.append(item["rationale"])
                lines.append("")

                if item.get("azure_enhanced_rationale"):
                    lines.append("**Azure-Enhanced Rationale:**")
                    lines.append("")
                    lines.append(item["azure_enhanced_rationale"])
                    lines.append("")

                if item.get("risk_indicators"):
                    lines.append("**Detected Risk Indicators:**")
                    lines.append("")
                    for risk in item["risk_indicators"]:
                        lines.append(f"- `{risk}`")
                    lines.append("")

                reference = item.get("reference", {})
                lines.append("**Retrieved Reference:**")
                lines.append("")
                lines.append(f"- **Source File:** {reference.get('source_file', '')}")
                lines.append(f"- **Reference Type:** {reference.get('reference_type', '')}")
                lines.append(f"- **Contract Type Hint:** {reference.get('contract_type_hint', '')}")
                lines.append(f"- **Reference Topic:** {reference.get('chunk_topic', '')}")
                lines.append(f"- **Retrieval Score:** {reference.get('score', 0.0)}")
                lines.append("")
                lines.append("**Reference Snippet:**")
                lines.append("")
                lines.append("> " + self._single_line(reference.get("snippet", "")))
                lines.append("")
                lines.append("---")
                lines.append("")

        return "\n".join(lines)

    def save_markdown(self, payload: Dict[str, object], output_path: str) -> None:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_markdown(payload), encoding="utf-8")

    def save_json(self, payload: Dict[str, object], output_path: str) -> None:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

    def _group_by_flag(self, results: List[Dict[str, object]]) -> Dict[str, List[Dict[str, object]]]:
        grouped = {
            "Green": [],
            "Amber": [],
            "Red": [],
            "Blue": [],
        }

        for result in results:
            flag = result.get("flag", "Blue")
            if flag not in grouped:
                flag = "Blue"
            grouped[flag].append(result)

        return grouped

    def _single_line(self, text: str) -> str:
        return " ".join(str(text).split())
